sudo: required
build: trusty
services:
  - xvfb
addons:
  apt:
    packages:
      - libgtk-3-dev
language: python
sudo: false
cache:
  pip: true

python:
  - '3.7'
matrix:
  fast_finish: true
before_install:
  - virtualenv .
  - bin/pip install pathlib2
  #- bin/pip3 install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.6-cp37-cp37m-linux_x86_64.whl -vvv wxPython
  - bin/pip install --upgrade -r requirements.txt

install:
  - wget https://gsdview.appspot.com/chromium-browser-official/chromium-83.0.4087.2.tar.xz
  - tar -xzf chromium-83.0.4087.2.tar.xz -C bin
  - export PATH=$(pwd)/bin:$PATH

script:
  - robot -d results Tests/TC_lifecycle.robot