services:
  - xvfb
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - libgtk-3-dev
      - google-chrome-stable
language: python
sudo: false
cache:
  pip: true

python:
  - '3.7'
matrix:
  fast_finish: true
before_install:
  - firefox -v
  - virtualenv .
  - bin/pip install pathlib2
  #- bin/pip3 install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.6-cp37-cp37m-linux_x86_64.whl -vvv wxPython
  - bin/pip install --upgrade -r requirements.txt

install:
  - wget "http://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - export PATH=$(pwd)/bin:$PATH

script:
  - robot -d results Tests/TC_milestone.robot