language: python
python:
  - "3.7.6"

install:
  - pip install -r requirements.txt
sudo: required
addons:
  chrome: stable

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master