language: python
python:
  - "3.7.6"

install:
  - pip install -r requirements.txt

before_script:
  - wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_mac64.zip
  - unzip chromedriver_mac64.zip -d /home/travis/virtualenv/python3.7.6/bin/
  - export CHROME_BIN=chromium-browser

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master