language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7.6"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install .
script:
  - robot -d results Tests/TestCases.robot
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master