language: python
sudo: false
services:
  - xvfb
addons:
  firefox: latest
  chrome: stable
  apt:
    source:
    - google-chrome
    packages:
    - libgtk-3-dev

cache:
  pip: true

python:
  - '3.7'
matrix:
  fast_finish: true
before_install:
  - npm install web-component-tester
  - npm install bower
  - export PATH=$pwd/node_modules/.bin:$PATH
  - pip install webdriver-manager
  - pip install -r requirements.txt

install:
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip -l chromedriver_linux64.zip -d bin
  - export PATH=$(pwd)/bin:$PATH

script:
  - robot -d results Tests/TC_milestone.robot