sudo: required
build: trusty
language: python
python:
  - "3.7.6"
addons:
  chrome: stable
 install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - npm install && node_modules/brunch/bin/brunch build --production
  - mix compile
  - mix phx.digest
  - pip install -r requirements.txt

  before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - nohup chromedriver &
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
  
install:
  - pip install -r requirements.txt

sudo: required
addons:
  chrome: stable

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master