sudo: required
build: trusty
language: python
python:
  - "3.7.6"
addons:
  chrome: stable

jobs:
include:
    - os: osx
      language: generic
  
before_script:
  - bundle exec rails runner "Webdrivers::Chromedriver.update"

install:
  - pip install -r requirements.txt

script:
  - robot -d results -v BROWSER:gc -i sanity tests

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master