sudo: required
build: trusty
language: python
python:
  - "3.7.6"
addons:
  apt:
    packages:
      - xvfb
      - dpkg
  chrome: stable

jobs:
include:
    - os: osx
      language: generic
  
before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"

before_script:
  - wget "https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_mac64.zip"
  - tar xfz chromedriver_mac64.zip
  - sudo mv geckodriver /usr/local/bin
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

install:
  - pip install -r requirements.txt

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master