sudo: required
build: trusty
language: python
python:
  - "3.7.6"
addons:
  chrome: stable

jobs:
include:
    - os: osx
      language: generic
  
before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_mac64.zip" -O
  - unzip chromedriver_mac64.zip -d ~/bin

install:
  - pip install -r requirements.txt

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master