sudo: required
build: trusty
language: python
python:
  - "3.7.6"
addons:
  chrome: stable

jobs:
include:
    - os: osx
      language: generic
  
before_script:
  - export PATH=$PATH:/usr/local/bin/chromedriver/

install:
  - pip install -r requirements.txt

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master