language: python
python:
  - "3.7.6"

before_install:

install:
  - pip install -r requirements.txt
  - virtualenv test-env --no-setuptools
  - mkdir -p buildout-cache/downloads
  
sudo: required
addons:
  chrome: stable

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master