language: python
python:
  - "3.7.6"

install:
  - pip install -r requirement.txt
  - pip install .
before_script:
  - easy_install distribute
  - pip install -r requirement.txt
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master