sudo: required
build: trusty
language: python
python:
  - "3.7.6"
jobs:
include:
    - os: osx
      language: generic
      env: TOXENV=py32
    - os: osx
      language: generic
      env: TOXENV=py33
    - os: osx
      language: generic
      env: PYTHON=3.7.6

before_script:
  - wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_mac64.zip
  - unzip chromedriver_mac64.zip -d /home/travis/virtualenv/python3.7.6/bin/
  - export CHROME_BIN=chromium-browser
  - echo $PATH
  
install:
  - pip install -r requirements.txt

sudo: required
addons:
  chrome: stable

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master