sudo: required
build: trusty
language: python
python:
  - "3.7.6"
addons:
  chrome: stable

jobs:
include:
    - os: osx
      language: generic
      env: TOXENV=py32
    - os: osx
      language: generic
      env: TOXENV=py33
    - os: osx
      language: generic
      env: PYTHON=3.7.6

before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - nohup chromedriver &

install:
  - pip install -r requirements.txt

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master