sudo: required
build: trusty
language: python
python:
  - "3.7.6"
jobs:
include:
    - os: osx
      language: generic
      env: TOXENV=py32
    - os: osx
      language: generic
      env: TOXENV=py33
    - os: osx
      language: generic
      env: PYTHON=3.7.6

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
install:
  - pip install -r requirements.txt

sudo: required
addons:
  chrome: stable

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master