sudo: required
build: trusty
language: python
python:
  - "3.7.6"
addons:
  apt:
    packages:
      - xvfb
      - dpkg
  chrome: stable

jobs:
include:
    - os: osx
      language: generic
  
before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0

install:
  - pip install -r requirements.txt

capabilities: [{
    browserName: 'chrome',
    'goog:chromeOptions': {
  args: ['--headless', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--window-size=1920,1080']
  },
  }],
};

script:
  - robot -d results Tests/TestCases.robot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master